### ISSUE TITLE
/chats; 39 строка; \н\а\х\у\я\ \в\с\ё\ \о\б\ф\у\с\ц\и\р\о\в\а\т\ь\?; Всё и так работать будет, не ссы

### ISSUE THREAD

**Issue by diveloper53** [SashaTalkStudio/SayOnlineWebLite#2]
Замени
echo date('G\:i\ \|\ d\.m\.Y\ \|\ ', $v['timestamp']) . htmlentities($v['sender']) . ' | ' . htmlentities($v['text']) . '<br>';
на
echo date('G:i | d.m.Y | ', $v['timestamp']) . htmlentities($v['sender']) . ' | ' . htmlentities($v['text']) . '<br>';

Не ссы ничё не сломается, а код станет приятней

**Comment by SashaTalk** [comment]
спасибо, воздержусь. мало ли че сломают в будущих версиях php, в пизду

**Comment by diveloper53** [comment]
Открой ська

Мы еще не договорили

**Comment by SashaTalk** [comment]
договаривай

**Comment by diveloper53** [comment]
> договаривай

Ты ведь прекрасно знаешь что больше никогда не будешь обновлять это говно, как и ты больше никогда не будешь обновлять сэй онлайн на батче, а если и обновишь то к старости, тогда почему он вдруг перестанет поддерживаться и сломается если оно никогда не обновиться до версии PHP 9 если конечно таковая когда нибуть выйдет и мы к тому времени не умрём от старости или еще чего, тогда опять же возникает вопрос: какого хуя ты пишешь говнокод, какого хуя ты пишешь сэй онлайн, какого хуя ты вообще кодишь, какого хуя ты закрываешь мои issue, какого хуя, а главное нахуя это всё надо, кстати говоря я бы хотел прорекламировать благодаря боту в ВК свой сайт, анонимный хостинг без регистрации и смс сделанный в качестве пет проекта работает 24/7 и нуждается в поддержке в виде того чтобы им кто-то пользовался хотябы, потом возможно я добавлю и начну втирать премиум, но функционал не ограничу, просто добавлю новый функционал чисто для премиума, а возможно даже сделаю по примеру убунту про, типо для бомжей бесплатно, короче заходите на https://anonhost.ga, и еще, я хочу написать этот текст настолько длинным чтобы тебе просто было лень его читать, незнаю получиться у меня или нет, но в общем была не была, кстати, зачем переносить базу данных на бомжаргу, а только потом выпускать обнову сэй онлайна, если ты можешь сначала выпустить сэй онлайн 1.5.1 или какая там у тебя версия я без понятия, а потом продолжить переносить сэй онлайн на бомжаргу, а лучше его вообще не переносить а сделать скрипт на бомжарге который будет поднимать сервер как только он будет падать, ну или по запросу от пользователей сэй онлайна, возможно такой скрипт для резервного копирования будет написать даже легче, типо я по такому принципу разрабатываю Assistants App чтоб ты знал, потому-что у него и так технический долг выше чем у всех версий сэй онлайна вместе взятых, в том числе и чай онлайн (пуэр), короче типо вот так вот, Assistants App работает, скажите спасибо, кстати, может мне переписать сэй онлайн на C#? Думаю будет забавно, если кто-то до этого момента дочитал с серьёзными намерениями я буду в ахуе, потому-что я уже заебался это писать, кстати говоря думаю что часть текста можно заполнить "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", как тебе идея? Думаю "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." звучит вполне прикольно, особенно если учесть тот факт что её можно полностью скопировать с википедии, а также если учесть что этот текст "рыба", как его называет википедия, не является оригиналом, оригинал звучит совсем по другому, вот, глянь: "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", кстати раньше она (википедия) была коммерческим проектом, но походу что-то явно не получилось, не фортануло, а так пацан к успеху шёл. Кстати, почему бы тебе не добавить в сэй онлайн пасхалку в виде этого текста "рыбы"? Думаю получилось бы забавно, а вообще, сэй онлайн давно бы пора обновить, добавить веб интерьфейс что ли, и не типо как лайт веб сэй онлайн, а уже наконец доделать обычный веб сэй онлайн, а то задрал уже в systemd рубиться, игроман хренов.

Короче открывай issue, и выпиливай этот говнокод, вопрос закрыт.

**Comment by SashaTalk** [comment]
> Ты ведь прекрасно знаешь что больше никогда не будешь обновлять это говно

буду. есть что пофиксить, и нужно будет обновить, чтобы поддерживал апи 0.2

> как и ты больше никогда не будешь обновлять сэй онлайн на батче

буду, 0.15 готов на 45%

> а если и обновишь то к старости

выпущу 0.14.2, когда допишу новый апи

> тогда почему он вдруг перестанет поддерживаться и сломается если оно никогда не обновиться до версии PHP 9 если конечно таковая когда нибуть выйдет и мы к тому времени не умрём от старости или еще чего

веб сервер, на котором размещён сей онлайн веб лайт, постоянно получает обновления php

> тогда опять же возникает вопрос: какого хуя ты пишешь говнокод

хочу и пишу. Сами же попросили опенсурснуть

> какого хуя ты пишешь сэй онлайн

это весело (нет) и приносит мне денежные средства

> какого хуя ты вообще кодишь

мне это нравится

> какого хуя ты закрываешь мои issue

к каждому issue я пишу, почему я их закрываю. почитай, если интересно

> какого хуя, а главное нахуя это всё надо

думаю, я говорил, что сей онлайн - это протест. Сначала доказывал всем: "ооо, смотрите, социальная сеть на батче и на Яндекс.Диске", а потом это превратилось в небольшую оппозицию против ВКонтакте и его политики развития социальной сети. Да, спасибо за клипы, а когда вы официальный клиент под Android собираетесь оптимизировать? Когда, там, баги в vk.com/im исправите? Ну, и всё в этом духе.

> кстати говоря я бы хотел прорекламировать благодаря боту в ВК свой сайт

твоё сообщение слишком длинное, и бот его не переварил

> просто добавлю новый функционал чисто для премиума

ты только что придумал Telegram Premium! осталось всего ничего: не добавлять функции для простых смертных.

> я хочу написать этот текст настолько длинным чтобы тебе просто было лень его читать, незнаю получиться у меня или нет

считай, что не получилось

> зачем переносить базу данных на бомжаргу, а только потом выпускать обнову сэй онлайна, если ты можешь сначала выпустить сэй онлайн 1.5.1 или какая там у тебя версия я без понятия

его делать долго. я так и хотел, просто мои люди надоели, мозги выносят. "кококо, апи медленный, кококо, апи падает" и т.п.. Хотя вообще по фактам разнесли, поэтому да, я пишу новый апи сейчас.

>  лучше его вообще не переносить а сделать скрипт на бомжарге который будет поднимать сервер как только он будет падать, ну или по запросу от пользователей сэй онлайна, возможно такой скрипт для резервного копирования будет написать даже легче

спасибо за совет, сей онлайн, считай, резервными копиями живёт. чинить сервер мгновенно? зачем? бомжарга будет проверять состояние сервера с катастрофически низкой скоростью, за это Яндексу отдельное спасибо.

> может мне переписать сэй онлайн на C#?

Возможно, вы имели ввиду: *может мне **переписать** сэй онлайн на C#?*. Твой клиент не будет официальным, потому что я не смогу его поддерживать, так что не надейся. Если хочешь, пиши свой, наберёшь себе пользовательскую базу. Удачи запустить свой клиент на машинах с Linux.

> Кстати, почему бы тебе не добавить в сэй онлайн пасхалку в виде этого текста "рыбы"?

вау, как бесполезно! сей онлайн на батче и так весит под 100 килобайт, так что, пожалуй, воздержусь.

> сэй онлайн давно бы пора обновить, добавить веб интерьфейс что ли, и не типо как лайт веб сэй онлайн, а уже наконец доделать обычный веб сэй онлайн,

если что, Say Online Web с "веб интерьфейсом" имеет [свой репозиторий](https://github.com/SashaTalkStudio/SayOnlineWeb) под открытой лицензией. Если так хочется, сделай это сам, буду благодарен.

> Короче открывай issue, и выпиливай этот говнокод, вопрос закрыт.

<https://github.com/SashaTalkStudio/SayOnlineWebLite/issues/2#issuecomment-1575091669>

**Comment by m-a-prod** [comment]
Все знают что сашок-лошок ленивое говно которое никогда не поднимет рабочий апи, а я поэтому никогда не сделаю крутой клиент на питоне, но все же блять Саша подними нормальную инфраструктуру ленивое ты говно. ГОЙДА

**Comment by SashaTalk** [comment]
для этого надо написать новый апи под новую БД и новый клиент. даже не знаю, что сложнее.
