### ISSUE TITLE
Мой браузер не поддерживает куки

### ISSUE THREAD

**Issue by diveloper53** [SashaTalkStudio/SayOnlineWebLite#5]
Придумай что нибуть, а то слишком тяжёлый твой сэй онлайн какой-то

**Comment by SashaTalk** [comment]
твой браузер не поддерживает куки => в твоём браузере нет JS => для твоего бразуера нет возможных способов использовать интерактивные страницы.

если честно, этот клиент я создал, чтобы посидеть в сей онлайне с Windows 95 и IE3
