### ISSUE TITLE
не тянет сей онлайн веб лайт

### ISSUE THREAD

**Issue by marnfrifnsk** [SashaTalkStudio/SayOnlineWebLite#6]
сижу с виндовс 3.1, пишу этот текст, браузер Netscape, почему твою каку сраку не тянет, бля? какие то куки сруки блять, я хочу пользоваться лучшей соц сетью в мире блять прямо здесь и сейчас

**Comment by SashaTalk** [comment]
докажи что с netscape в гитхабе сидишь

**Comment by marnfrifnsk** [comment]
что такое нетскапе

**Comment by SashaTalk** [comment]
интернет-обозреватель

**Comment by marnfrifnsk** [comment]
обозреватель это типа китай бугага чтоли?

**Comment by SashaTalk** [comment]
это обзорщик

**Comment by marnfrifnsk** [comment]
это синонимы

**Comment by SashaTalk** [comment]
тебе виднее

**Comment by marnfrifnsk** [comment]
пися попа
